version: '3.8'

services:
  chatbot-server:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: chatbot-server
    ports:
      - "5001:5001"
    environment:
      - PORT:5001
      - NODE_ENV=dev
      - REDIS_HOST=chatbot-redis
      - REDIS_PORT=6379        
    depends_on:
      - chatbot-redis          
    volumes:
      - ./:/app            
      - /app/node_modules
    networks:
      - app-network            

  chatbot-redis:
    image: redis:latest
    container_name: chatbot-redis
    ports:
      - "6379:6379"          
    networks:
      - app-network       

networks:
  app-network:
    driver: bridge            
